import { Artist } from '../types/artist.type';

export const artists: Artist[] = [
  {
    id: '6719b7df513ec3990a90b3bf',
    name: 'Hokusai',
    dateOfBirth: '1760',
    dateOfDeath: '1849',
    bio: 'Famous for his woodblock prints, particularly The Great Wave off Kanagawa.',
    country: 'Japan',
  },
  {
    id: '6719b81ae0c4efd2bcdde666',
    name: 'Sesshū Tōyō',
    dateOfBirth: '1420',
    dateOfDeath: '1506',
    bio: 'A master of ink painting (sumi-e) during the Muromachi period.',
    country: 'Japan',
  },
  {
    id: '6719b86aee87a2172a891e7b',
    name: 'Gu Kaizhi',
    dateOfBirth: 'c. 344',
    dateOfDeath: '406',
    bio: 'Known for his figure paintings and is one of China’s most prominent early painters.',
    country: 'China',
  },
  {
    id: '6719b8786843574a47a86907',
    name: 'Zhao Mengfu',
    dateOfBirth: '1254',
    dateOfDeath: '1322',
    bio: 'A Yuan Dynasty painter and calligrapher, highly regarded in Chinese art history.',
    country: 'China',
  },
  {
    id: '6719b8933263f6b74a95c07a',
    name: 'Ravi Varma',
    dateOfBirth: '1848',
    dateOfDeath: '1906',
    bio: 'Known for blending Indian themes with European academic art techniques, particularly in his depiction of Hindu gods and goddesses.',
    country: 'India',
  },
  {
    id: '6719b8c042d7c6e079029107',
    name: 'Yayoi Kusama',
    dateOfBirth: '1929',
    dateOfDeath: '',
    bio: 'Renowned for her polka dots and immersive infinity mirror installations.',
    country: 'Japan',
  },
  {
    id: '6719b8eb142908e716109318',
    name: 'Takashi Murakami',
    dateOfBirth: '1962',
    dateOfDeath: '',
    bio: 'Known for blending high and low culture in his "Superflat" style and collaborations with major brands.',
    country: 'Japan',
  },
  {
    id: '6719b901400ad3defefaec1b',
    name: 'Ai Weiwei',
    dateOfBirth: '1957',
    dateOfDeath: '',
    bio: 'A contemporary artist and political activist known for his provocative art installations and sculptures.',
    country: 'China',
  },
  {
    id: '6719b9542a41cd7e308a614d',
    name: 'Nam June Paik',
    dateOfBirth: '1932',
    dateOfDeath: '2006',
    bio: 'A pioneer of video art and often referred to as the “father of video art.”',
    country: 'South Korea',
  },
  {
    id: '6719b96828bad3235102f4d4',
    name: 'Bharti Kher',
    dateOfBirth: '1969',
    dateOfDeath: '',
    bio: 'A contemporary artist known for her work with bindi motifs and her exploration of cultural and gender identities.',
    country: 'India',
  },
  {
    id: '6719b985dd1eea2c00e3b228',
    name: 'Lee Ufan',
    dateOfBirth: '1936',
    dateOfDeath: '',
    bio: 'A leader of the Mono-ha ("School of Things") movement, known for minimalistic sculptures and paintings focusing on materiality.',
    country: 'South Korea',
  },
];
